// Generated by gencpp from file test3/turtlesrv.msg
// DO NOT EDIT!


#ifndef TEST3_MESSAGE_TURTLESRV_H
#define TEST3_MESSAGE_TURTLESRV_H

#include <ros/service_traits.h>


#include <test3/turtlesrvRequest.h>
#include <test3/turtlesrvResponse.h>


namespace test3
{

struct turtlesrv
{

typedef turtlesrvRequest Request;
typedef turtlesrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct turtlesrv
} // namespace test3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test3::turtlesrv > {
  static const char* value()
  {
    return "cbc75de5a4fb9f83b2d98718a6d2f59b";
  }

  static const char* value(const ::test3::turtlesrv&) { return value(); }
};

template<>
struct DataType< ::test3::turtlesrv > {
  static const char* value()
  {
    return "test3/turtlesrv";
  }

  static const char* value(const ::test3::turtlesrv&) { return value(); }
};


// service_traits::MD5Sum< ::test3::turtlesrvRequest> should match
// service_traits::MD5Sum< ::test3::turtlesrv >
template<>
struct MD5Sum< ::test3::turtlesrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test3::turtlesrv >::value();
  }
  static const char* value(const ::test3::turtlesrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test3::turtlesrvRequest> should match
// service_traits::DataType< ::test3::turtlesrv >
template<>
struct DataType< ::test3::turtlesrvRequest>
{
  static const char* value()
  {
    return DataType< ::test3::turtlesrv >::value();
  }
  static const char* value(const ::test3::turtlesrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test3::turtlesrvResponse> should match
// service_traits::MD5Sum< ::test3::turtlesrv >
template<>
struct MD5Sum< ::test3::turtlesrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test3::turtlesrv >::value();
  }
  static const char* value(const ::test3::turtlesrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test3::turtlesrvResponse> should match
// service_traits::DataType< ::test3::turtlesrv >
template<>
struct DataType< ::test3::turtlesrvResponse>
{
  static const char* value()
  {
    return DataType< ::test3::turtlesrv >::value();
  }
  static const char* value(const ::test3::turtlesrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST3_MESSAGE_TURTLESRV_H
